name: reg_page
description: A Flutter package for handling welcome page user authentication and authorization with setting page
version: 0.0.1
homepage: https://github.com/Zakariya5567/reg_page.git
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  in_app_purchase: ^3.1.11
  url_launcher: ^6.2.1
  sn_progress_dialog: ^1.1.4
  path_provider: ^2.1.3
  archive: ^3.4.10
  permission_handler: ^11.3.1
  app_tracking_transparency: ^2.0.5
  http: ^1.2.2
  upgrader: ^11.3.1
  flutter_jhg_elements:
    path: ../flutter_jhg_elements
    # git:
    #   url: https://github.com/jamie2364/flutter_jhg_elements
    #   ref: main
  get_it: ^7.7.0
  animated_custom_dropdown: ^3.1.1
  device_info_plus: ^11.1.1
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/jhg_background.png
    - assets/images/jhg_sign.png
    - assets/images/jhg_logo.png
    - assets/images/icon_cross.png
    - assets/images/Copy of MUSICTOOLS.png

  fonts:
    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
        - asset: fonts/SourceSans3-Italic.ttf
          style: italic
        - asset: fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: fonts/SourceSans3-SemiBold.ttf
          weight: 600

  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
